  deploy-to-vm:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy container on remote VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ needs.build-and-push.outputs.TAG }}
            docker stop fastapi-crud || true
            docker rm fastapi-crud || true
            docker run -d --name fastapi-crud -p 8000:80000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ needs.build-and-push.outputs.TAG }}
          EOF
