name: Build and Deploy Docker Image

on: workflow_dispatch  # Executa apenas manualmente, não em push


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      TAG: ${{ steps.docker_tag.outputs.TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker tag
        id: docker_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="${GITHUB_SHA::7}"
          fi
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ steps.docker_tag.outputs.TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ steps.docker_tag.outputs.TAG }}

  deploy-to-vm:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy container on remote VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ needs.build-and-push.outputs.TAG }}
            docker stop fastapi-crud || true
            docker rm fastapi-crud || true
            docker run -d --name fastapi-crud -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ needs.build-and-push.outputs.TAG }}
          EOF
